# Generated by Django 4.2 on 2023-04-09 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_todoitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='title',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='todo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.todo'),
        ),
    ]
